### ISSUE TITLE
Error when printing 'Windows not supported' log

### ISSUE THREAD

**Issue by nickmi** [jpmorganchase/quorum-wizard#62]
![image](https://user-images.githubusercontent.com/2481323/81571031-125c8c80-93aa-11ea-9d07-def1bcfd1086.png)

When running the quorum-wizard the above error shows up
Node v14.2.0
Windows 10

**Comment by bmcd87** [comment]
Quorum Wizard doesn't work on Windows yet, but we are looking into making it work on windows when using only docker-compose mode. It's supposed to show a message saying that Windows isn't supported, but it looks like it's failing when it tries to print that log. We'll fix that.

In the meantime I would recommend using virtual box or vagrant to run a linux vm. Then you will be able to run the wizard/quorum from inside that vm.

**Comment by bmcd87** [comment]
I made an issue to tracker windows support progress here: #63
