### ISSUE TITLE
Improve messaging about required dependencies in both the readme and wizard console output

### ISSUE THREAD

**Issue by nickmi** [jpmorganchase/quorum-wizard#64]
when quorum-wizard quickstart option completes and i try to start the network by using
./start.sh i get the following

![image](https://user-images.githubusercontent.com/2481323/81691835-2cf43b80-9466-11ea-83fb-a1dd276d7ac9.png)

![image](https://user-images.githubusercontent.com/2481323/81691875-38476700-9466-11ea-80b3-18f8ab7f8b51.png)

Ubuntu 20.04 server
java 11
node 12.16.3

**Comment by nickmi** [comment]
purging the network seems to have fixed the problem

**Comment by bmcd87** [comment]
That XmlElement error usually means the java versions are mismatched. The wizard looks at your current java version and decides which version of tessera to use automatically. So could be that you were using Java 8 when you generated the network, but were using Java 11 when you tried to run it.

**Comment by nickmi** [comment]
This is true as i did not have java installed in the beginning , i believe that java could be listed as a dependency in the readme as it is the only thing not automatically installed.

Cheers

**Comment by bmcd87** [comment]
Yep, we will make it clearer that this is a required dependency when using bash + tessera/cakeshop. Thanks!
